# Generated by Django 3.1.1 on 2021-04-14 23:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterNumber', models.IntegerField()),
                ('image_id', models.IntegerField()),
                ('medroid_image_id', models.IntegerField()),
                ('task_id', models.CharField(default='', max_length=400)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'imf_cluster_summary',
            },
        ),
        migrations.CreateModel(
            name='ImageSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50)),
                ('file_name', models.TextField()),
                ('imageURL', models.TextField()),
                ('group', models.TextField()),
                ('username', models.TextField()),
                ('timeStamp', models.PositiveIntegerField()),
                ('country', models.TextField()),
                ('numComments', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
                ('platform', models.TextField()),
                ('PHash', models.CharField(max_length=200)),
                ('PHash_gs', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'imf_image_summary',
            },
        ),
        migrations.CreateModel(
            name='PHashSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1_id', models.IntegerField()),
                ('image2_id', models.IntegerField()),
                ('task_id', models.CharField(max_length=400)),
                ('ham_dist', models.PositiveIntegerField()),
                ('identical', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'imf_phash_summary',
            },
        ),
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.IntegerField()),
                ('task_id', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'imf_task_summary',
            },
        ),
    ]
